### ISSUE TITLE
CryptoDataset failure

### ISSUE THREAD

**Issue by AlconDivino** [huseinzol05/Stock-Prediction-Models#17]
I tried to use LSTM as well as vanilla-2path for prediction.
With the GOOG-year.csv dataset everything went right , but when using the btcusd.csv dataset from TensorTom or even getting my own Data from the bitmex exchange (same format as GOOG-year.csv) I get following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[{{node rnn/TensorArrayStack/TensorArrayGatherV3}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LSTM_Custom.py", line 177, in <module>
    LSTM(exchange='bitmex' , symbol='BTC/USD' , start_date='2018-05-01T00:00:00Z' , timeframe='1d' , future_day=50 , fetch_size=25)
  File "LSTM_Custom.py", line 136, in LSTM
    modelnn.hidden_layer: init_value,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[node rnn/TensorArrayStack/TensorArrayGatherV3 (defined at LSTM_Custom.py:41) ]]

Caused by op 'rnn/TensorArrayStack/TensorArrayGatherV3', defined at:
  File "LSTM_Custom.py", line 177, in <module>
    LSTM(exchange='bitmex' , symbol='BTC/USD' , start_date='2018-05-01T00:00:00Z' , timeframe='1d' , future_day=50 , fetch_size=25)
  File "LSTM_Custom.py", line 83, in LSTM
    0.01, num_layers, df_log.shape[1], size_layer, df_log.shape[1], dropout_rate
  File "LSTM_Custom.py", line 41, in __init__
    drop, self.X, initial_state = self.hidden_layer, dtype = tf.float32
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn.py", line 671, in dynamic_rnn
    dtype=dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn.py", line 883, in _dynamic_rnn_loop
    final_outputs = tuple(ta.stack() for ta in output_final_ta)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn.py", line 883, in <genexpr>
    final_outputs = tuple(ta.stack() for ta in output_final_ta)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_ops.py", line 1128, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_ops.py", line 292, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_ops.py", line 306, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 6291, in tensor_array_gather_v3
    element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[node rnn/TensorArrayStack/TensorArrayGatherV3 (defined at LSTM_Custom.py:41) ]]

```

Any idea why that happens? CSV file from TensorTom: https://github.com/TensorTom/Timeseries-Prediction-Models/blob/master/dataset/btcusd.csv

**Comment by huseinzol05** [comment]
Need to optimize the code for your own dataset
